### PR TITLE
Upgrade client-go to new version

### PR DESCRIPTION
**Pull request by uthark**
Stumbled over the issue that kube2iam can't AssumeRole for the pod.

Error that pods receives:
```
upgrade-manager-75966d7867-h9dr5 rolling-upgrade-controller time="2020-03-04T17:32:38Z" level=info msg="NoCredentialProviders: no valid providers in chain\ncaused by: EnvAccessKeyNotFound: failed to find credentials in the environment.\nSharedCredsLoad: failed to load profile, .\nEC2RoleRequestError: no EC2 instance role found\ncaused by: EC2MetadataError: failed to make EC2Metadata request\ncaused by: pod with specified IP not found\n"
```

Error in kube2iam:

```
E0304 17:33:33.671001       1 reflector.go:199] github.com/jtblin/kube2iam/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Pod: Get "https://10.231.0.1:443/api/v1/pods?fieldSelector=spec.nodeName%3Dip-172-16-114-8.us-west-2.compute.internal&resourceVersion=0": http2: no cached connection was available
```

Found this issue: https://github.com/golang/go/issues/22091

Tried to upgrade dependencies, but at the end of the day upgraded most of them.

Please take a look.

Also, I'm wondering about the status of the repo?

/cc @grosser

### CODE REVIEW

**Comment by grosser** [comment]
bunch of conflicts :(

**Comment by uthark** [comment]
Rebased on top of the latest master.

**Comment by mwhittington21** [comment]
I've used the contents of this as a part of #263 - I didn't want to merge this as is and then go on without enabling go mod properly as I've tried to manage k8s dependencies in other projects without go mod and it's a bit of a nightmare these days.

**Comment by uthark** [comment]
Nice there is go mod support. Thank you!

**Pull request merged**
