### PR TITLE
Fix #241 by removing x-forwarded-for header from request to aws

### LINKED ISSUE #241: Add support for Instance Metadata Service Version 2 (IMDSv2)
AWS announced the Instance Metadata Service Version 2 (IMDSv2) which is already deployed and supported by the latests SDKs:

https://aws.amazon.com/about-aws/whats-new/2019/11/announcing-updates-amazon-ec2-instance-metadata-service/

The SDKs now try to do a `PUT` request to get the Session Token, which Kube2IAM answers with 403. Then the SDKs fall back the the IMDSv1 and work fine, but it causes warnings in the logs and is also reflected in the metrics.

It would be great if in future Kube2IAM would also implement IMDSv2.

### PR DESCRIPTION
**Pull request by DaspawnW**
Copy solution used in KIAM also to kube2iam to fix #241

### CODE REVIEW

**Comment by DaspawnW** [comment]
Hey @rbvigilante ,
Sorry simply copy pasted the stuff from kiam.  For me it works as expected ;-)
https://github.com/uswitch/kiam/blob/6c1999c40337a7c5d8c02880f756d5ada5e7a569/pkg/aws/metadata/handler_proxy.go#L49

**Comment by rbvigilante** [comment]
In Kiam, the header is removed from all valid requests (Kiam filters requests to the metadata API with a "whitelist" regexp [here](https://github.com/uswitch/kiam/blob/6c1999c40337a7c5d8c02880f756d5ada5e7a569/pkg/aws/metadata/handler_proxy.go#L47)).

That said, if it works, awesome. I made the Kiam change under the impression that the header needed to be removed from all requests, but looking again there isn't really any good documentation that says this is the case, so maybe it's just the token address. 🎉

**Comment by jochen42** [comment]
for me the change works fine in production since 2 weeks.

**Comment by gferon** [comment]
Please merge this fix, it's exactly what we're looking for!

**Review by mwhittington21 — APPROVED** [review]
LGTM

**Comment by jhuntwork** [comment]
> Please excuse me if I'm wrong here, but I _think_ the x-forwarded-for header will need to be removed from all paths for IMDSv2 to work

I think you are correct. See #279

**Comment by ahmsb8884** [comment]
Team, after upgrade from 10.1 to 10.11 am getting a lot of these. how should I set the args in pod to avoid these?

```
time="2021-08-13T19:18:19Z" level=error msg="Error getting instance id Get \"http://169.254.169.254/latest/meta-data/instance-id\": dial tcp 169.254.169.254:80: i/o timeout"
time="2021-08-13T19:18:49Z" level=error msg="Error getting instance id Get \"http://169.254.169.254/latest/meta-data/instance-id\": dial tcp 169.254.169.254:80: i/o timeout"
time="2021-08-13T19:19:19Z" level=error msg="Error getting instance id Get \"http://169.254.169.254/latest/meta-data/instance-id\": dial tcp 169.254.169.254:80: i/o timeout"
```

**Comment by ahmsb8884** [comment]
What is means? I still don't understand how to get rid of timeout errors in kube2iam 10.11 version.

**Pull request merged**
