### PR TITLE
added README to clairify calico and EKS

### PR DESCRIPTION
**Pull request by vchan2002**
Added a bit of info to clarify that EKS can also run Calico too..... I learned that the hard way myself...

### CODE REVIEW

**Comment by jrnt30** [comment]
Thanks

**Comment by robinjoseph08** [comment]
@vchan2002 correct me if I'm wrong, but I believe those instructions on the AWS docs to setup Calico is only setting it up for network policies. I just installed it on a brand new EKS cluster and the network interfaces didn't change to `cali+`. It's still using `eni+` from `amazon-vpc-cni-k8s`.

**Comment by jrnt30** [comment]
It's based upon the CNI provider that you choose.  The default for EKS would be the `amazon-vpc-cni-k8s` and result in `eni+` as I understand it, that is correct. 

Not exactly sure how to structure the docs so they cater to different levels of depth and understanding there.

**Comment by robinjoseph08** [comment]
Ahh gotcha. I think the confusion for me stemmed from the specific link that is included (https://docs.aws.amazon.com/eks/latest/userguide/calico.html). If you follow the instructions at the link, it doesn't change the underlying CNI AFAIK. It just enables the network policies, but it still uses `amazon-vpc-cni-k8s`. So maybe it could link to a page that does show how to actually use replace `amazon-vpc-cni-k8s` with Calico?

**Pull request merged**
