### PR TITLE
make configurable the cache refresh interval

### PR DESCRIPTION
**Pull request by ltagliamonte-dd**
Making the cache refresh interval configurable.
Trying to address/alleviate this issue https://github.com/jtblin/kube2iam/issues/244

### CODE REVIEW

**Comment by ltagliamonte-dd** [comment]
@jtblin or repo admin do you mind have a look at this please?

**Comment by ltagliamonte-dd** [comment]
maybe @Jacobious52 or @SharpEdgeMarshall can have a look at this?

**Comment by Jacobious52** [comment]
Sure I'll have a look and test this out

**Comment by ltagliamonte-dd** [comment]
thank you @Jacobious52

**Pull request merged**
