### PR TITLE
update base image to mitigate CVE's

### PR DESCRIPTION
**Pull request by pgvishnuram**
#### What this PR does / why we need it:
The current base image 3.12 has multiple CVE's , to mitigate the issues we are updating the base image 
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist chart
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by krmichelos** [comment]
@jtblin @ccarlfjord @walkafwalka @mariusv Any chance this can get reviewed/merged?

**Review by mariusv — APPROVED** [review]
LGTM 👍

**Comment by krmichelos** [comment]
@jtblin @ccarlfjord @walkafwalka now that this is reviewed can it be merged and released

**Comment by whipermr5** [comment]
Any chance this will be released soon?

**Comment by zuvman** [comment]
Also looking to know if this will be released soon?

**Comment by krmichelos** [comment]
@jtblin @ccarlfjord @walkafwalka Thank you for getting this merged, however it isn't available in a released version

**Comment by walkafwalka** [comment]
> @jtblin @ccarlfjord @walkafwalka Thank you for getting this merged, however it isn't available in a released version

The other maintainers do not have access to DockerHub. @jtblin is the only one.

I would suggest either building and hosting the image yourself or using AWS' IAM for Service Accounts.

**Comment by jtblin** [comment]
Travis will push the image to docker hub if it has a tag, I'll try and look
into it tomorrow.

**Comment by dmcdii** [comment]
@jtblin any update?
Thank you

**Comment by Janesee3** [comment]
Hi @jtblin , any updates on when this can be pushed to docker? Thanks!

**Comment by jtblin** [comment]
It's now pushed, sorry for the lag.

**Pull request merged**
