### PR TITLE
Support IMDSv2 

### LINKED ISSUE #282: kube2iam IMDSv2 support
Hello,
I'm trying to use IMDSv2 with kube2iam (version 0.10.11). When I change instance metadata to force only IMDSv2 usage (with AWS-CLI), kube2iam throws error:

`time="2020-09-28T08:23:23Z" level=error msg="Error getting instance id, got status: 401 Unauthorized"
time="2020-09-28T08:23:23Z" level=info msg="Listening on port 8181"`

and restarts, getting into crashLoopbackOff. When I revert, with support to IMDSv2 and v1, kube2iam starts to work.
What should I do to benefit from IMDSv2?

Kind regards,
mimek

### LINKED ISSUE #300: kube2iam:2.6.0 not working with metadata version v2
Hi @jtblin I am using kube2iam-2.6.0 with EKS version 1.17+ when i deploy the kube2iam pod it goes in crashloopbackoff with the error as `time="2021-02-10T08:04:19Z" level=fatal msg="EC2 Metadata is not available, are you running on EC2?"` . Whereas the ec2 instance seems to be running . Do i need to change anything in setup i have also added the following in instance user data

TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` \
&& curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/
curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/ami-id

### PR DESCRIPTION
**Pull request by msiuts**
#### What this PR does / why we need it:

This PRs makes Kube2IAM compatible with IMDSv2 .

It updates all the dependencies, mainly to upgrade to an aws-sdk which support IMDSv2 and also merges 
https://github.com/jtblin/kube2iam/pull/304 already, which fixes the health check.

Since alle dependencies are updated, this includes the K8S api.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #300
  - fixes #282

#### Checklist chart
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped

### CODE REVIEW

**Comment by hajnej** [comment]
I forked @msiuts repo and built own image as a workaround. Would be fine to have this PR merged :)

**Comment by dix-icomys** [comment]
@jtblin @ccarlfjord @walkafwalka @mariusv Any chance this can get reviewed and merged?
Thanks

**Comment by msiuts** [comment]
If there is an interest I could also update everything once more on this PR, since I am now also running a fork of this. Just let me know.

**Comment by paranoidd** [comment]
Hello! I was wondering what is necessary to get this PR merged, this fix is relevant to my work. I have forked @msiuts repository, and am running this fix in my organization successfully - however we only use it within AWS.

**Comment by brunzefb** [comment]
I second @paranoidd's question.  If kube2iam can be made to work with IMDSv2, that is better.  Security scanners will flag clusters that have instances allowing IMDSv1, and we need special code to tell AWS to allow IMDSv1 when creating a cluster. I am discussing some of these issues in a blogpost [which you can find here](https://brunzema.com/blog/2022/11/26/a-python-boto-tool-to-automatically-enable-logs-on-all-my-elb-load-balancers-part-2/)

**Comment by nullck** [comment]
Please, I'd like to have this PR merged.

**Comment by msiuts** [comment]
I just removed the merge conflicts and added the latest version of the aws-sdk.
Normally I would also update other dependencies and also the Go version in `go.mod` but I did not want to derail this PR. Let me know if I can support any further.

**Comment by janquijano** [comment]
Any reason why this PR is not merged yet?

**Comment by xmengkinaxis** [comment]
What is the suggested workaround for this problem, since the fix is not merged yet?

**Comment by mikefossa** [comment]
@msiuts that would be great!

**Comment by protosam** [comment]
@xmengkinaxis you could build the fork and push a copy to ghcr while waiting for the merge we all need.

**Comment by vgrudenic** [comment]
@msiuts thanks for creating this!

I am slightly confused by why the "official fix" in 0.10.11 isn't working, perhaps you can shine some light please? I noticed PRs #270 and #279 (merged to 0.10.11) were supposed to fix these issues, but we are still getting 401 errors when we enable IMDSv2. Do you know why these stopped working? Was something changed on the AWS side in the meantime?

**Comment by protosam** [comment]
I wouldn't be surprised if those prior changes didn't actually work.

**Comment by msiuts** [comment]
@vgrudenic As said in the description, this PR here does upgrade to an [AWS SDK which supports [](IMDBSv2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/use-a-supported-sdk-version-for-imdsv2.html)) and includes another PR which fixes the health check.

As you can see in the link v1.8.7 of the Go SDK does not yet support it.

I can not remember the exact behaviour at this time without this PR (which is becoming 2 years old in September), maybe just try out an official version and document it here in the thread if this important to you.

**Comment by benbertrands** [comment]
Hi. Can this be merged?

**Review by riadhnamely — APPROVED** [review]

**Comment by protosam** [comment]
Would be great to see this get merged. I've been waiting to delete my package for over half a year now: https://github.com/users/protosam/packages/container/package/kube2iam-pr325

**Comment by hkhrais** [comment]
Can this be merged - hopefully in 2023 :D @riadhnamely

**Pull request closed without merging**
